export const metadata = {
  title: 'Product detail',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children, params
}: {
  children: React.ReactNode,
  params: ProductDetailParams
}) {
  return (
    <>
      {children}
      <h2>features of product {params.productId}</h2>
    </>
  )
}

type ProductDetailParams = {
  productId: string
}