export const metadata = {
  title: 'Product detail',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children, params
}: Props) {
  return (
    <>
      {children}
      <h2>features of product {params.productId}</h2>
    </>
  )
}

type Props = {
  children: React.ReactNode,
  params: {
    productId:string
  }
}