export const metadata = {
  title: 'Auth',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode,
}) {
  return (
    <>
      <h1>Layout for login and register page</h1>
      {children}
      <h1>Layout for login and register page</h1>
    </>
  )
}