import { Metadata } from "next"

export const metadata: Metadata = {
  // title: 'Next.js',

  title: {
    default: 'default if page not add metadata',
    template: '%s | nexjs pro vip'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <p>Header nè</p>
        </header>
        <main>
          {children}
        </main>
        <footer>
          <p>Footer nè</p>
        </footer>
      </body>
    </html>
  )
}
